(SELECT JOB_ID FROM EMPLOYEES
    WHERE HIRE_DATE BETWEEN TO_DATE ('1990-01-01', 'yyyy-mm-dd') AND 
        TO_DATE('1990-06-30', 'yyyy-mm-dd'))
intersect
(SELECT JOB_ID FROM EMPLOYEES
    WHERE HIRE_DATE BETWEEN TO_DATE ('1990101-01', 'yyyy-mm-dd') AND 
        TO_DATE('1991-06-30', 'yyyy-mm-dd'));


-- SQL5 
-- Ejercicio 2
SELECT * FROM EMPLOYEES
    WHERE LAST_NAME LIKE 'J%' OR 
        LAST_NAME LIKE 'K%' OR 
            LAST_NAME LIKE 'L%' OR 
                LAST_NAME LIKE 'M%';

-- Ejercicio 10                
SELECT LAST_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC FETCH FIRST 3 ROWS ONLY;


-- SQL7
-- Ejercicio 2
SELECT CNOMBRE FROM PERTENECE WHERE CNOMBRE LIKE 'C%' 
    AND NUMRED IN (SELECT NUMRED_ENVIA FROM ENVIA_ENERGIA)
    AND NUMRED NOT IN (SELECT NUMRED_RECIBE FROM ENVIA_ENERGIA);
-- Ejercicio 9
