create or replace FUNCTION LISTADO_PELICULAS_FUNCTION 
    RETURN VARCHAR2 IS
    RESULT VARCHAR2(32767);
    CURSOR CURSOR_PELICULAS IS SELECT CODPELICULA, TITULO FROM PELICULAS;
    CURSOR CURSOR_CINES(CPELI PELICULAS.CODPELICULA%TYPE) IS SELECT CODCINE 
        FROM SALAS S, PROYECTAN P WHERE P.CODPELICULA=CPELI 
            AND P.CODSALA=S.CODSALA GROUP BY CODCINE;
    CURSOR CURSOR_SALAS(CCINE CINES.CODCINE%TYPE, CPELI PELICULAS.CODPELICULA%TYPE) IS SELECT S.CODSALA, P.SESION, SUM(P.ENTRADASVENDIDAS) AS N_ESPECTADORES
        FROM SALAS S, PROYECTAN P WHERE S.CODCINE=CCINE
            AND S.CODSALA=P.CODSALA AND P.CODPELICULA=CPELI GROUP BY S.CODSALA, P.SESION;
BEGIN
    FOR I IN CURSOR_PELICULAS LOOP
        RESULT:=RESULT||'Titulo: '||I.TITULO||'\n';
        FOR J IN CURSOR_CINES(I.CODPELICULA) LOOP
            RESULT:=RESULT||'  Cine '||J.CODCINE||'\n';
            FOR K IN CURSOR_SALAS(J.CODCINE, I.CODPELICULA) LOOP
                RESULT:=RESULT||'      Sala '||K.CODSALA||' - Sesión: '||K.SESION||' - Nº Espectadores: '||K.N_ESPECTADORES||'\n';
            END LOOP;
        END LOOP;
    END LOOP;
    RETURN RESULT;
END;

DECLARE 
    RESULT VARCHAR2(32767);
BEGIN
    RESULT:=LISTADO_PELICULAS_FUNCTION;
    DBMS_OUTPUT.PUT_LINE(RESULT);
END;

execute LISTADO_PELICULAS;