DROP TABLE wears;
DROP TABLE maillot;
DROP TABLE takes_part;
DROP TABLE cyclist;
DROP TABLE is_sponsorized;
DROP TABLE team;
DROP TABLE sponsor;
DROP TABLE comes;
DROP TABLE pairs_with;
DROP TABLE agent;
DROP TABLE incident;
DROP TABLE passes;
DROP TABLE goes_by;
DROP TABLE terrainmunicipality;
DROP TABLE tsection;
DROP TABLE area;
DROP TABLE road;
DROP TABLE mountainstage;
DROP TABLE stage;


CREATE TABLE stage 
(
	num_stage DECIMAL(2), 
	km DECIMAL(3), 
	date_stage DATE, 
	PRIMARY KEY(num_stage), 
	CHECK(km>=0)
);

CREATE TABLE mountainstage 
(
	num_stage DECIMAL(2), 
	category_mountain VARCHAR(50), 
	altitude DECIMAL(4),
	points_winner DECIMAL(3),
	PRIMARY KEY(num_stage), 
	FOREIGN KEY(num_stage) REFERENCES stage(num_stage), 
	CHECK(altitude>=0),
	CHECK(points_winner>=0)
);

CREATE TABLE road 
(
	id_road CHAR(4), 
	name_road VARCHAR(50), 
	type_road VARCHAR(50), 
	length_road DECIMAL(4), 
	PRIMARY KEY(id_road), 
	CHECK(length_road>=0)
);

CREATE TABLE area
(
	name_area VARCHAR(50), 
	surface_area DECIMAL(3), 
	PRIMARY KEY(name_area), 
	CHECK(surface_area>=0)
);

CREATE TABLE tsection 
(
	order_road DECIMAL(3), 
	id_road CHAR(4), 
	length_section DECIMAL(3), 
	name_area VARCHAR(50),
	PRIMARY KEY(order_road, id_road), 
	FOREIGN KEY (id_road) REFERENCES road(id_road),
	FOREIGN KEY(name_area) REFERENCES area(name_area), 
	CHECK(length_section>=0)
);

CREATE TABLE terrainmunicipality 
(
	id_tm CHAR(4), 
	name_tm VARCHAR(50), 
	town_tm VARCHAR(50), 
	PRIMARY KEY(id_tm), 
	CHECK(town_tm>=0)
);

CREATE TABLE goes_by 
(
	num_stage DECIMAL(2), 
	order_road DECIMAL(3), 
	id_road CHAR(4),
	PRIMARY KEY(num_stage, order_road, id_road), 
	FOREIGN KEY(num_stage) REFERENCES stage(num_stage), 
	FOREIGN KEY(order_road, id_road) REFERENCES tsection (order_road,id_road)
);

CREATE TABLE passes 
(
	order_road DECIMAL(3), 
	id_road CHAR(4), 
	id_tm CHAR(4), 
	km_entry DECIMAL(4), 
	km_exit DECIMAL(4),
	PRIMARY KEY(order_road, id_road, id_tm), 
	FOREIGN KEY(order_road, id_road) REFERENCES tsection (order_road,id_road), 
	FOREIGN KEY(id_tm) REFERENCES terrainmunicipality(id_tm), 
	CHECK(km_entry>=0), 
	CHECK(km_exit>=0)
);

CREATE TABLE incident 
(
	id_incident CHAR(4), 
	date_incident DATE, 
	descrip_incident VARCHAR(50), 
	order_road DECIMAL(3), 
	id_road CHAR(4), 
	PRIMARY KEY(id_incident), 
	FOREIGN KEY(order_road, id_road) REFERENCES tsection (order_road, id_road)
);

CREATE TABLE agent 
(
	licence CHAR(6), 
	name_agent VARCHAR(50), 
	seniority DATE, 
	PRIMARY KEY(licence)
);

CREATE TABLE pairs_with 
(
	licence1 CHAR(6), 
	licence2 CHAR(6), 
	PRIMARY KEY(licence1, licence2), 
	FOREIGN KEY(licence1) REFERENCES agent(licence), 
	FOREIGN KEY(licence2) REFERENCES agent(licence)
);

CREATE TABLE comes 
(
	id_incident CHAR(4), 
	licence1 CHAR(6), 
	licence2 CHAR(6), 
	PRIMARY KEY(id_incident, licence1, licence2), 
	FOREIGN KEY(id_incident) REFERENCES incident (id_incident), 
	FOREIGN KEY(licence1, licence2) REFERENCES pairs_with(licence1, licence2)
);

CREATE TABLE sponsor 
(
	id_sponsor CHAR(4), 
	name_sponsor VARCHAR(50), 
	id_tm CHAR(4), 
	PRIMARY KEY(id_sponsor),
	FOREIGN KEY(id_tm) REFERENCES terrainmunicipality(id_tm)
);

CREATE TABLE team 
(
	name_team VARCHAR(50), 
	city_team VARCHAR(50), 
	budget DECIMAL(5), 
	PRIMARY KEY(name_team),
	CHECK(budget>=0)
);

CREATE TABLE is_sponsorized
(
	name_team VARCHAR(50), 
	id_sponsor CHAR(4), 
	amount DECIMAL(5), 
	PRIMARY KEY(name_team, id_sponsor), 
	FOREIGN KEY(name_team) REFERENCES team(name_team),
	FOREIGN KEY(id_sponsor) REFERENCES sponsor (id_sponsor), 
	CHECK(amount>=0)
);

CREATE TABLE cyclist 
(
	cyclist_name VARCHAR(50), 
	category_cyclist VARCHAR(50), 
	type_cyclist VARCHAR(50), 
	name_team VARCHAR(50), 
	PRIMARY KEY(cyclist_name), 
	FOREIGN KEY(name_team) REFERENCES team(name_team)
);

CREATE TABLE takes_part
(
	num_stage DECIMAL(2), 
	cyclist_name VARCHAR(50), 
	order_classification DECIMAL(2), 
	PRIMARY KEY(num_stage, cyclist_name), 
	FOREIGN KEY(num_stage) REFERENCES stage(num_stage), 
	FOREIGN KEY(cyclist_name) REFERENCES cyclist(cyclist_name), 
	CHECK(order_classification>=0)
);

CREATE TABLE maillot
(
	id_maillot CHAR(4), 
	color VARCHAR(10), 
	meaning VARCHAR(50), 
	PRIMARY KEY(id_maillot)
);

CREATE TABLE wears 
(
	num_stage DECIMAL(2), 
	cyclist_name VARCHAR(50), 
	id_maillot CHAR(4), 
	PRIMARY KEY(num_stage, cyclist_name, id_maillot), 
	FOREIGN KEY(num_stage, cyclist_name) REFERENCES takes_part (num_stage, cyclist_name), 
	FOREIGN KEY(id_maillot) REFERENCES maillot(id_maillot)
);

DELETE FROM WEARS;
DELETE FROM MAILLOT;
DELETE FROM TAKES_PART;
DELETE FROM CYCLIST;
DELETE FROM IS_SPONSORIZED;
DELETE FROM TEAM;
DELETE FROM SPONSOR;
DELETE FROM COMES;
DELETE FROM PAIRS_WITH;
DELETE FROM AGENT;
DELETE FROM INCIDENT;
DELETE FROM PASSES;
DELETE FROM GOES_BY;
DELETE FROM TERRAINMUNICIPALITY;
DELETE FROM TSECTION;
DELETE FROM AREA;
DELETE FROM ROAD;
DELETE FROM MOUNTAINSTAGE;
DELETE FROM STAGE;
INSERT INTO STAGE (NUM_STAGE,KM,DATE_STAGE) VALUES ('1','180',to_date('01/09/2016','DD/MM/YYYY'));
INSERT INTO STAGE (NUM_STAGE,KM,DATE_STAGE) VALUES ('2','186',to_date('02/09/2016','DD/MM/YYYY'));
INSERT INTO STAGE (NUM_STAGE,KM,DATE_STAGE) VALUES ('3','172',to_date('03/09/2016','DD/MM/YYYY'));
INSERT INTO STAGE (NUM_STAGE,KM,DATE_STAGE) VALUES ('4','163',to_date('04/09/2016','DD/MM/YYYY'));
INSERT INTO STAGE (NUM_STAGE,KM,DATE_STAGE) VALUES ('5','181',to_date('05/09/2016','DD/MM/YYYY'));
INSERT INTO STAGE (NUM_STAGE,KM,DATE_STAGE) VALUES ('6','169',to_date('06/09/2016','DD/MM/YYYY'));
INSERT INTO STAGE (NUM_STAGE,KM,DATE_STAGE) VALUES ('7','195',to_date('07/09/2016','DD/MM/YYYY'));
INSERT INTO STAGE (NUM_STAGE,KM,DATE_STAGE) VALUES ('8','153',to_date('08/09/2016','DD/MM/YYYY'));
INSERT INTO STAGE (NUM_STAGE,KM,DATE_STAGE) VALUES ('9','163',to_date('09/09/2016','DD/MM/YYYY'));
INSERT INTO STAGE (NUM_STAGE,KM,DATE_STAGE) VALUES ('10','186',to_date('10/09/2016','DD/MM/YYYY'));
INSERT INTO STAGE (NUM_STAGE,KM,DATE_STAGE) VALUES ('11','165',to_date('11/09/2016','DD/MM/YYYY'));
INSERT INTO STAGE (NUM_STAGE,KM,DATE_STAGE) VALUES ('12','162',to_date('12/09/2016','DD/MM/YYYY'));
INSERT INTO STAGE (NUM_STAGE,KM,DATE_STAGE) VALUES ('13','164',to_date('13/09/2016','DD/MM/YYYY'));
INSERT INTO STAGE (NUM_STAGE,KM,DATE_STAGE) VALUES ('14','159',to_date('14/09/2016','DD/MM/YYYY'));
INSERT INTO STAGE (NUM_STAGE,KM,DATE_STAGE) VALUES ('15','183',to_date('15/09/2016','DD/MM/YYYY'));
INSERT INTO STAGE (NUM_STAGE,KM,DATE_STAGE) VALUES ('16','152',to_date('16/09/2016','DD/MM/YYYY'));
INSERT INTO STAGE (NUM_STAGE,KM,DATE_STAGE) VALUES ('17','169',to_date('17/09/2016','DD/MM/YYYY'));
INSERT INTO STAGE (NUM_STAGE,KM,DATE_STAGE) VALUES ('18','198',to_date('18/09/2016','DD/MM/YYYY'));
INSERT INTO STAGE (NUM_STAGE,KM,DATE_STAGE) VALUES ('19','183',to_date('19/09/2016','DD/MM/YYYY'));
INSERT INTO STAGE (NUM_STAGE,KM,DATE_STAGE) VALUES ('20','159',to_date('20/09/2016','DD/MM/YYYY'));
INSERT INTO STAGE (NUM_STAGE,KM,DATE_STAGE) VALUES ('21','189',to_date('21/09/2016','DD/MM/YYYY'));
INSERT INTO MOUNTAINSTAGE (NUM_STAGE,CATEGORY_MOUNTAIN,ALTITUDE,POINTS_WINNER) VALUES ('4','especial','1784','42');
INSERT INTO MOUNTAINSTAGE (NUM_STAGE,CATEGORY_MOUNTAIN,ALTITUDE,POINTS_WINNER) VALUES ('5','primera','1075','30');
INSERT INTO MOUNTAINSTAGE (NUM_STAGE,CATEGORY_MOUNTAIN,ALTITUDE,POINTS_WINNER) VALUES ('9','primera','1353','43');
INSERT INTO MOUNTAINSTAGE (NUM_STAGE,CATEGORY_MOUNTAIN,ALTITUDE,POINTS_WINNER) VALUES ('10','especial','1449','35');
INSERT INTO MOUNTAINSTAGE (NUM_STAGE,CATEGORY_MOUNTAIN,ALTITUDE,POINTS_WINNER) VALUES ('16','especial','1303','33');
INSERT INTO MOUNTAINSTAGE (NUM_STAGE,CATEGORY_MOUNTAIN,ALTITUDE,POINTS_WINNER) VALUES ('17','tercera','1650','48');
INSERT INTO MOUNTAINSTAGE (NUM_STAGE,CATEGORY_MOUNTAIN,ALTITUDE,POINTS_WINNER) VALUES ('18','segunda','1006','48');
INSERT INTO ROAD (ID_ROAD,NAME_ROAD,TYPE_ROAD,LENGTH_ROAD) VALUES ('1   ','C4','comarcal','41');
INSERT INTO ROAD (ID_ROAD,NAME_ROAD,TYPE_ROAD,LENGTH_ROAD) VALUES ('2   ','L10','local','15');
INSERT INTO ROAD (ID_ROAD,NAME_ROAD,TYPE_ROAD,LENGTH_ROAD) VALUES ('3   ','N6','nacional','104');
INSERT INTO ROAD (ID_ROAD,NAME_ROAD,TYPE_ROAD,LENGTH_ROAD) VALUES ('4   ','C9','comarcal','22');
INSERT INTO ROAD (ID_ROAD,NAME_ROAD,TYPE_ROAD,LENGTH_ROAD) VALUES ('5   ','L9','local','18');
INSERT INTO ROAD (ID_ROAD,NAME_ROAD,TYPE_ROAD,LENGTH_ROAD) VALUES ('6   ','N6','nacional','141');
INSERT INTO ROAD (ID_ROAD,NAME_ROAD,TYPE_ROAD,LENGTH_ROAD) VALUES ('7   ','N6','nacional','71');
INSERT INTO ROAD (ID_ROAD,NAME_ROAD,TYPE_ROAD,LENGTH_ROAD) VALUES ('8   ','L1','local','20');
INSERT INTO ROAD (ID_ROAD,NAME_ROAD,TYPE_ROAD,LENGTH_ROAD) VALUES ('9   ','N8','nacional','52');
INSERT INTO ROAD (ID_ROAD,NAME_ROAD,TYPE_ROAD,LENGTH_ROAD) VALUES ('10  ','L7','local','16');
INSERT INTO ROAD (ID_ROAD,NAME_ROAD,TYPE_ROAD,LENGTH_ROAD) VALUES ('11  ','C2','comarcal','37');
INSERT INTO ROAD (ID_ROAD,NAME_ROAD,TYPE_ROAD,LENGTH_ROAD) VALUES ('12  ','L9','local','13');
INSERT INTO ROAD (ID_ROAD,NAME_ROAD,TYPE_ROAD,LENGTH_ROAD) VALUES ('13  ','N4','nacional','101');
INSERT INTO ROAD (ID_ROAD,NAME_ROAD,TYPE_ROAD,LENGTH_ROAD) VALUES ('14  ','N8','nacional','94');
INSERT INTO ROAD (ID_ROAD,NAME_ROAD,TYPE_ROAD,LENGTH_ROAD) VALUES ('15  ','L6','local','13');
INSERT INTO ROAD (ID_ROAD,NAME_ROAD,TYPE_ROAD,LENGTH_ROAD) VALUES ('16  ','L10','local','11');
INSERT INTO ROAD (ID_ROAD,NAME_ROAD,TYPE_ROAD,LENGTH_ROAD) VALUES ('17  ','L8','local','13');
INSERT INTO ROAD (ID_ROAD,NAME_ROAD,TYPE_ROAD,LENGTH_ROAD) VALUES ('18  ','L5','local','20');
INSERT INTO ROAD (ID_ROAD,NAME_ROAD,TYPE_ROAD,LENGTH_ROAD) VALUES ('19  ','L6','local','12');
INSERT INTO ROAD (ID_ROAD,NAME_ROAD,TYPE_ROAD,LENGTH_ROAD) VALUES ('20  ','C2','comarcal','32');
INSERT INTO AREA (NAME_AREA,SURFACE_AREA) VALUES ('aces','167');
INSERT INTO AREA (NAME_AREA,SURFACE_AREA) VALUES ('bayo','117');
INSERT INTO AREA (NAME_AREA,SURFACE_AREA) VALUES ('godos','86');
INSERT INTO AREA (NAME_AREA,SURFACE_AREA) VALUES ('seana','173');
INSERT INTO AREA (NAME_AREA,SURFACE_AREA) VALUES ('pendas','129');
INSERT INTO AREA (NAME_AREA,SURFACE_AREA) VALUES ('lorio','74');
INSERT INTO AREA (NAME_AREA,SURFACE_AREA) VALUES ('torce','67');
INSERT INTO AREA (NAME_AREA,SURFACE_AREA) VALUES ('ponce','64');
INSERT INTO AREA (NAME_AREA,SURFACE_AREA) VALUES ('ques','115');
INSERT INTO AREA (NAME_AREA,SURFACE_AREA) VALUES ('vitos','148');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('1','1   ','10','bayo');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('2','1   ','6','godos');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('3','1   ','9','godos');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('4','1   ','8','vitos');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('1','2   ','9','aces');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('2','2   ','9','torce');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('1','3   ','9','bayo');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('2','3   ','7','seana');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('1','4   ','5','seana');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('2','4   ','6','ponce');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('1','5   ','9','aces');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('1','6   ','5','seana');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('2','6   ','9','seana');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('1','7   ','7','lorio');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('2','7   ','5','bayo');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('1','8   ','10','vitos');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('2','8   ','6','godos');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('1','9   ','5','bayo');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('2','9   ','8','torce');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('3','9   ','7','godos');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('1','10  ','5','torce');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('1','11  ','5','pendas');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('2','11  ','5','godos');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('3','11  ','9','lorio');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('4','11  ','5','lorio');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('5','11  ','9','aces');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('6','11  ','7','pendas');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('1','12  ','7','torce');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('1','13  ','6','seana');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('1','15  ','9','lorio');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('2','15  ','8','bayo');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('3','15  ','10','bayo');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('4','15  ','7','godos');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('5','15  ','8','pendas');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('6','15  ','8','ponce');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('1','16  ','5','pendas');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('2','16  ','5','godos');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('3','16  ','6','aces');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('1','17  ','8','vitos');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('2','17  ','5','aces');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('3','17  ','9','pendas');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('1','18  ','8','bayo');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('2','18  ','6','lorio');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('3','18  ','6','vitos');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('1','19  ','7','seana');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('2','19  ','5','bayo');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('3','19  ','8','ponce');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('4','19  ','8','pendas');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('5','19  ','6','seana');
INSERT INTO TSECTION (ORDER_ROAD,ID_ROAD,LENGTH_SECTION,NAME_AREA) VALUES ('1','20  ','8','godos');
INSERT INTO TERRAINMUNICIPALITY (ID_TM,NAME_TM,TOWN_TM) VALUES ('1   ','alange','18042');
INSERT INTO TERRAINMUNICIPALITY (ID_TM,NAME_TM,TOWN_TM) VALUES ('2   ','alborea','24613');
INSERT INTO TERRAINMUNICIPALITY (ID_TM,NAME_TM,TOWN_TM) VALUES ('3   ','almarza','16879');
INSERT INTO TERRAINMUNICIPALITY (ID_TM,NAME_TM,TOWN_TM) VALUES ('4   ','balazote','25003');
INSERT INTO TERRAINMUNICIPALITY (ID_TM,NAME_TM,TOWN_TM) VALUES ('5   ','barca','10512');
INSERT INTO TERRAINMUNICIPALITY (ID_TM,NAME_TM,TOWN_TM) VALUES ('6   ','caltojar','16546');
INSERT INTO TERRAINMUNICIPALITY (ID_TM,NAME_TM,TOWN_TM) VALUES ('7   ','deza','8492');
INSERT INTO TERRAINMUNICIPALITY (ID_TM,NAME_TM,TOWN_TM) VALUES ('8   ','fuentes','27808');
INSERT INTO TERRAINMUNICIPALITY (ID_TM,NAME_TM,TOWN_TM) VALUES ('9   ','gormaz','1500');
INSERT INTO TERRAINMUNICIPALITY (ID_TM,NAME_TM,TOWN_TM) VALUES ('10  ','jorquera','6781');
INSERT INTO TERRAINMUNICIPALITY (ID_TM,NAME_TM,TOWN_TM) VALUES ('11  ','magas','7766');
INSERT INTO TERRAINMUNICIPALITY (ID_TM,NAME_TM,TOWN_TM) VALUES ('12  ','molinos','18824');
INSERT INTO TERRAINMUNICIPALITY (ID_TM,NAME_TM,TOWN_TM) VALUES ('13  ','noalejo','11811');
INSERT INTO TERRAINMUNICIPALITY (ID_TM,NAME_TM,TOWN_TM) VALUES ('14  ','nolay','15619');
INSERT INTO TERRAINMUNICIPALITY (ID_TM,NAME_TM,TOWN_TM) VALUES ('15  ','ontar','16644');
INSERT INTO TERRAINMUNICIPALITY (ID_TM,NAME_TM,TOWN_TM) VALUES ('16  ','orcera','970');
INSERT INTO TERRAINMUNICIPALITY (ID_TM,NAME_TM,TOWN_TM) VALUES ('17  ','rena','22405');
INSERT INTO TERRAINMUNICIPALITY (ID_TM,NAME_TM,TOWN_TM) VALUES ('18  ','riodar','9352');
INSERT INTO TERRAINMUNICIPALITY (ID_TM,NAME_TM,TOWN_TM) VALUES ('19  ','risco','27112');
INSERT INTO TERRAINMUNICIPALITY (ID_TM,NAME_TM,TOWN_TM) VALUES ('20  ','rus','24344');
INSERT INTO TERRAINMUNICIPALITY (ID_TM,NAME_TM,TOWN_TM) VALUES ('21  ','sabiote','21033');
INSERT INTO TERRAINMUNICIPALITY (ID_TM,NAME_TM,TOWN_TM) VALUES ('22  ','saloma','14070');
INSERT INTO TERRAINMUNICIPALITY (ID_TM,NAME_TM,TOWN_TM) VALUES ('23  ','salos','3808');
INSERT INTO TERRAINMUNICIPALITY (ID_TM,NAME_TM,TOWN_TM) VALUES ('24  ','siros','7676');
INSERT INTO TERRAINMUNICIPALITY (ID_TM,NAME_TM,TOWN_TM) VALUES ('25  ','socovo','3201');
INSERT INTO TERRAINMUNICIPALITY (ID_TM,NAME_TM,TOWN_TM) VALUES ('26  ','tejosa','6088');
INSERT INTO TERRAINMUNICIPALITY (ID_TM,NAME_TM,TOWN_TM) VALUES ('27  ','torrena','12546');
INSERT INTO TERRAINMUNICIPALITY (ID_TM,NAME_TM,TOWN_TM) VALUES ('28  ','villara','12915');
INSERT INTO TERRAINMUNICIPALITY (ID_TM,NAME_TM,TOWN_TM) VALUES ('29  ','voleno','29805');
INSERT INTO TERRAINMUNICIPALITY (ID_TM,NAME_TM,TOWN_TM) VALUES ('30  ','zarzo','17949');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('1','2','2   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('1','3','15  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('2','1','3   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('2','6','15  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('3','1','15  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('3','1','16  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('3','1','3   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('3','1','7   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('3','2','3   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('4','1','16  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('4','1','4   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('4','1','6   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('4','2','2   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('4','2','4   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('4','3','1   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('4','4','1   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('6','1','15  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('6','2','2   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('6','6','11  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('7','1','12  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('7','1','4   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('7','1','5   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('7','2','4   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('8','1','12  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('8','1','4   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('8','2','3   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('8','4','15  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('8','6','15  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('9','1','12  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('9','1','13  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('9','1','15  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('9','1','4   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('9','2','15  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('10','1','13  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('10','2','15  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('10','4','15  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('11','1','5   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('11','4','15  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('11','5','11  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('12','2','4   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('12','3','15  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('12','6','11  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('13','1','2   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('13','1','5   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('13','2','15  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('13','3','15  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('14','1','16  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('14','1','5   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('14','1','6   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('14','2','3   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('14','2','4   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('14','6','15  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('15','1','5   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('15','5','15  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('16','1','3   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('16','2','2   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('16','2','7   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('16','2','8   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('16','4','15  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('17','1','3   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('17','2','4   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('17','6','11  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('18','1','13  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('18','2','15  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('18','2','6   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('19','1','13  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('19','1','15  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('19','1','4   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('19','2','1   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('19','6','11  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('20','1','1   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('20','1','12  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('20','1','8   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('20','2','4   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('20','5','11  ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('21','1','3   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('21','1','4   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('21','2','2   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('21','2','3   ');
INSERT INTO GOES_BY (NUM_STAGE,ORDER_ROAD,ID_ROAD) VALUES ('21','5','15  ');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','1   ','23  ','3','5');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','1   ','25  ','0','2');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','1   ','26  ','2','3');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','1   ','3   ','0','1');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','1   ','8   ','3','7');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','1   ','22  ','1','3');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('3','1   ','4   ','2','7');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('3','1   ','22  ','0','1');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('3','1   ','27  ','1','2');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('4','1   ','5   ','3','5');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('4','1   ','12  ','5','7');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('4','1   ','30  ','0','3');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','2   ','1   ','4','7');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','2   ','5   ','3','4');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','2   ','25  ','0','3');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','2   ','2   ','5','8');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','2   ','17  ','0','4');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','2   ','19  ','4','5');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','3   ','10  ','1','4');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','3   ','20  ','0','1');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','3   ','25  ','4','5');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','3   ','4   ','1','6');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','3   ','12  ','0','1');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','3   ','29  ','6','9');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','4   ','5   ','4','6');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','4   ','8   ','0','1');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','4   ','20  ','1','4');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','4   ','12  ','0','3');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','4   ','22  ','3','7');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','4   ','30  ','7','12');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','5   ','5   ','0','1');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','5   ','25  ','4','7');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','5   ','26  ','1','4');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','6   ','14  ','5','6');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','6   ','15  ','6','10');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','6   ','20  ','0','5');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','6   ','13  ','7','9');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','6   ','15  ','5','7');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','6   ','30  ','0','5');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','7   ','4   ','0','4');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','7   ','17  ','5','9');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','7   ','23  ','4','5');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','7   ','13  ','4','7');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','7   ','25  ','1','4');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','7   ','28  ','0','1');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','8   ','7   ','0','5');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','8   ','11  ','15','18');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','8   ','14  ','14','15');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','8   ','28  ','9','14');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','8   ','29  ','5','9');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','8   ','4   ','18','19');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','8   ','4   ','3','5');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','8   ','10  ','5','9');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','8   ','21  ','0','3');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','9   ','1   ','0','4');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','9   ','3   ','14','15');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','9   ','4   ','15','16');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','9   ','6   ','4','7');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','9   ','11  ','12','14');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','9   ','30  ','7','12');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','9   ','9   ','8','13');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','9   ','13  ','0','4');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','9   ','21  ','13','15');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','9   ','30  ','4','8');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('3','9   ','9   ','0','5');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('3','9   ','5   ','5','7');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('3','9   ','13  ','12','16');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('3','9   ','27  ','7','12');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','10  ','2   ','0','4');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','10  ','4   ','4','9');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','10  ','9   ','17','21');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','10  ','18  ','14','17');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','10  ','20  ','21','24');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','10  ','28  ','9','14');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','11  ','6   ','6','7');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','11  ','11  ','0','4');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','11  ','20  ','4','6');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','11  ','21  ','12','14');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','11  ','23  ','7','12');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','11  ','6   ','14','15');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','11  ','7   ','0','3');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','11  ','8   ','4','9');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','11  ','15  ','3','4');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','11  ','17  ','10','14');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','11  ','19  ','9','10');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('3','11  ','2   ','16','20');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('3','11  ','13  ','5','7');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('3','11  ','16  ','7','9');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('3','11  ','7   ','9','11');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('3','11  ','19  ','11','16');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('3','11  ','25  ','0','5');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('4','11  ','1   ','6','9');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('4','11  ','14  ','5','6');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('4','11  ','21  ','0','5');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('5','11  ','5   ','0','2');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('5','11  ','7   ','9','11');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('5','11  ','11  ','11','14');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('5','11  ','6   ','14','16');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('5','11  ','10  ','5','9');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('5','11  ','23  ','2','5');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('6','11  ','10  ','19','23');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('6','11  ','15  ','12','16');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('6','11  ','26  ','5','10');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('6','11  ','29  ','16','19');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('6','11  ','30  ','0','5');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('6','11  ','25  ','10','12');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','12  ','11  ','0','4');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','12  ','24  ','4','8');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','12  ','28  ','8','11');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','13  ','6   ','9','14');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','13  ','14  ','4','9');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','13  ','15  ','0','4');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','15  ','1   ','4','6');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','15  ','13  ','0','4');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','15  ','28  ','6','8');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','15  ','4   ','3','4');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','15  ','11  ','0','1');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','15  ','19  ','12','13');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','15  ','20  ','4','8');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','15  ','24  ','8','12');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','15  ','26  ','1','3');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('3','15  ','3   ','5','7');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('3','15  ','8   ','3','5');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('3','15  ','10  ','0','3');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('3','15  ','15  ','7','12');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('3','15  ','17  ','12','14');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('3','15  ','18  ','14','18');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('4','15  ','7   ','0','4');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('4','15  ','8   ','9','13');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('4','15  ','25  ','4','9');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('5','15  ','2   ','12','16');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('5','15  ','4   ','1','2');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('5','15  ','6   ','18','23');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('5','15  ','13  ','9','12');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('5','15  ','21  ','16','17');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('5','15  ','22  ','0','1');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('5','15  ','23  ','17','18');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('5','15  ','24  ','2','6');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('5','15  ','27  ','6','9');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('6','15  ','11  ','7','10');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('6','15  ','12  ','10','12');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('6','15  ','19  ','5','7');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('6','15  ','24  ','0','3');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('6','15  ','27  ','3','5');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','16  ','17  ','1','4');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','16  ','20  ','4','6');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','16  ','30  ','0','1');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','16  ','9   ','0','1');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','16  ','14  ','5','7');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','16  ','17  ','1','5');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('3','16  ','3   ','2','7');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('3','16  ','22  ','7','11');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('3','16  ','25  ','0','2');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','17  ','15  ','0','5');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','17  ','20  ','5','9');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','17  ','25  ','9','12');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','17  ','28  ','0','1');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','17  ','29  ','1','3');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','17  ','30  ','3','8');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('3','17  ','3   ','6','8');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('3','17  ','7   ','1','6');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('3','17  ','28  ','0','1');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','18  ','5   ','0','3');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','18  ','27  ','5','6');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','18  ','28  ','3','5');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','18  ','7   ','6','7');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','18  ','19  ','0','4');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','18  ','24  ','4','6');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('3','18  ','1   ','0','5');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('3','18  ','14  ','5','9');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('3','18  ','17  ','9','11');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','19  ','15  ','10','15');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','19  ','24  ','5','10');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','19  ','26  ','0','5');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','19  ','15  ','5','6');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','19  ','28  ','6','11');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('2','19  ','29  ','0','5');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('3','19  ','5   ','0','4');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('3','19  ','7   ','7','10');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('3','19  ','14  ','4','7');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('4','19  ','2   ','9','11');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('4','19  ','19  ','11','12');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('4','19  ','21  ','0','1');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('4','19  ','24  ','2','5');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('4','19  ','25  ','5','9');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('4','19  ','30  ','1','2');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('5','19  ','4   ','0','1');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('5','19  ','5   ','17','21');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('5','19  ','8   ','1','6');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('5','19  ','10  ','12','17');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('5','19  ','12  ','11','12');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('5','19  ','17  ','6','11');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('5','19  ','26  ','21','26');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','20  ','9   ','8','13');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','20  ','15  ','4','8');
INSERT INTO PASSES (ORDER_ROAD,ID_ROAD,ID_TM,KM_ENTRY,KM_EXIT) VALUES ('1','20  ','19  ','0','4');
INSERT INTO INCIDENT (ID_INCIDENT,DATE_INCIDENT,DESCRIP_INCIDENT,ORDER_ROAD,ID_ROAD) VALUES ('1   ',to_date('06/01/2016','DD/MM/YYYY'),'salida de via','1','1   ');
INSERT INTO INCIDENT (ID_INCIDENT,DATE_INCIDENT,DESCRIP_INCIDENT,ORDER_ROAD,ID_ROAD) VALUES ('2   ',to_date('16/09/2016','DD/MM/YYYY'),'hielo','2','1   ');
INSERT INTO INCIDENT (ID_INCIDENT,DATE_INCIDENT,DESCRIP_INCIDENT,ORDER_ROAD,ID_ROAD) VALUES ('3   ',to_date('07/04/2016','DD/MM/YYYY'),'averia','6','15  ');
INSERT INTO INCIDENT (ID_INCIDENT,DATE_INCIDENT,DESCRIP_INCIDENT,ORDER_ROAD,ID_ROAD) VALUES ('4   ',to_date('30/01/2016','DD/MM/YYYY'),'animales sueltos','1','16  ');
INSERT INTO INCIDENT (ID_INCIDENT,DATE_INCIDENT,DESCRIP_INCIDENT,ORDER_ROAD,ID_ROAD) VALUES ('5   ',to_date('08/12/2016','DD/MM/YYYY'),'animales sueltos','2','16  ');
INSERT INTO INCIDENT (ID_INCIDENT,DATE_INCIDENT,DESCRIP_INCIDENT,ORDER_ROAD,ID_ROAD) VALUES ('6   ',to_date('12/03/2016','DD/MM/YYYY'),'hielo','3','16  ');
INSERT INTO INCIDENT (ID_INCIDENT,DATE_INCIDENT,DESCRIP_INCIDENT,ORDER_ROAD,ID_ROAD) VALUES ('7   ',to_date('01/07/2016','DD/MM/YYYY'),'averia','1','17  ');
INSERT INTO INCIDENT (ID_INCIDENT,DATE_INCIDENT,DESCRIP_INCIDENT,ORDER_ROAD,ID_ROAD) VALUES ('8   ',to_date('21/12/2016','DD/MM/YYYY'),'choque','2','17  ');
INSERT INTO INCIDENT (ID_INCIDENT,DATE_INCIDENT,DESCRIP_INCIDENT,ORDER_ROAD,ID_ROAD) VALUES ('9   ',to_date('09/03/2016','DD/MM/YYYY'),'choque','3','17  ');
INSERT INTO INCIDENT (ID_INCIDENT,DATE_INCIDENT,DESCRIP_INCIDENT,ORDER_ROAD,ID_ROAD) VALUES ('10  ',to_date('13/11/2016','DD/MM/YYYY'),'averia','1','18  ');
INSERT INTO INCIDENT (ID_INCIDENT,DATE_INCIDENT,DESCRIP_INCIDENT,ORDER_ROAD,ID_ROAD) VALUES ('11  ',to_date('17/07/2016','DD/MM/YYYY'),'salida de via','2','18  ');
INSERT INTO INCIDENT (ID_INCIDENT,DATE_INCIDENT,DESCRIP_INCIDENT,ORDER_ROAD,ID_ROAD) VALUES ('12  ',to_date('21/05/2016','DD/MM/YYYY'),'hielo','3','18  ');
INSERT INTO INCIDENT (ID_INCIDENT,DATE_INCIDENT,DESCRIP_INCIDENT,ORDER_ROAD,ID_ROAD) VALUES ('13  ',to_date('23/07/2016','DD/MM/YYYY'),'averia','1','19  ');
INSERT INTO INCIDENT (ID_INCIDENT,DATE_INCIDENT,DESCRIP_INCIDENT,ORDER_ROAD,ID_ROAD) VALUES ('14  ',to_date('29/09/2016','DD/MM/YYYY'),'indisposicion conductor','4','15  ');
INSERT INTO INCIDENT (ID_INCIDENT,DATE_INCIDENT,DESCRIP_INCIDENT,ORDER_ROAD,ID_ROAD) VALUES ('15  ',to_date('27/03/2016','DD/MM/YYYY'),'choque','5','15  ');
INSERT INTO INCIDENT (ID_INCIDENT,DATE_INCIDENT,DESCRIP_INCIDENT,ORDER_ROAD,ID_ROAD) VALUES ('16  ',to_date('09/05/2016','DD/MM/YYYY'),'averia','6','15  ');
INSERT INTO INCIDENT (ID_INCIDENT,DATE_INCIDENT,DESCRIP_INCIDENT,ORDER_ROAD,ID_ROAD) VALUES ('17  ',to_date('31/07/2016','DD/MM/YYYY'),'indisposicion conductor','1','16  ');
INSERT INTO INCIDENT (ID_INCIDENT,DATE_INCIDENT,DESCRIP_INCIDENT,ORDER_ROAD,ID_ROAD) VALUES ('18  ',to_date('20/02/2016','DD/MM/YYYY'),'animales sueltos','2','16  ');
INSERT INTO INCIDENT (ID_INCIDENT,DATE_INCIDENT,DESCRIP_INCIDENT,ORDER_ROAD,ID_ROAD) VALUES ('19  ',to_date('24/12/2016','DD/MM/YYYY'),'animales sueltos','3','16  ');
INSERT INTO INCIDENT (ID_INCIDENT,DATE_INCIDENT,DESCRIP_INCIDENT,ORDER_ROAD,ID_ROAD) VALUES ('20  ',to_date('05/09/2016','DD/MM/YYYY'),'indisposicion conductor','3','9   ');
INSERT INTO INCIDENT (ID_INCIDENT,DATE_INCIDENT,DESCRIP_INCIDENT,ORDER_ROAD,ID_ROAD) VALUES ('21  ',to_date('22/12/2016','DD/MM/YYYY'),'averia','1','10  ');
INSERT INTO INCIDENT (ID_INCIDENT,DATE_INCIDENT,DESCRIP_INCIDENT,ORDER_ROAD,ID_ROAD) VALUES ('22  ',to_date('08/02/2016','DD/MM/YYYY'),'indisposicion conductor','1','11  ');
INSERT INTO INCIDENT (ID_INCIDENT,DATE_INCIDENT,DESCRIP_INCIDENT,ORDER_ROAD,ID_ROAD) VALUES ('23  ',to_date('05/04/2016','DD/MM/YYYY'),'choque','2','11  ');
INSERT INTO INCIDENT (ID_INCIDENT,DATE_INCIDENT,DESCRIP_INCIDENT,ORDER_ROAD,ID_ROAD) VALUES ('24  ',to_date('09/04/2016','DD/MM/YYYY'),'hielo','3','11  ');
INSERT INTO INCIDENT (ID_INCIDENT,DATE_INCIDENT,DESCRIP_INCIDENT,ORDER_ROAD,ID_ROAD) VALUES ('25  ',to_date('11/09/2016','DD/MM/YYYY'),'salida de via','4','11  ');
INSERT INTO INCIDENT (ID_INCIDENT,DATE_INCIDENT,DESCRIP_INCIDENT,ORDER_ROAD,ID_ROAD) VALUES ('26  ',to_date('09/04/2016','DD/MM/YYYY'),'salida de via','5','11  ');
INSERT INTO INCIDENT (ID_INCIDENT,DATE_INCIDENT,DESCRIP_INCIDENT,ORDER_ROAD,ID_ROAD) VALUES ('27  ',to_date('04/01/2016','DD/MM/YYYY'),'animales sueltos','6','11  ');
INSERT INTO INCIDENT (ID_INCIDENT,DATE_INCIDENT,DESCRIP_INCIDENT,ORDER_ROAD,ID_ROAD) VALUES ('28  ',to_date('06/02/2016','DD/MM/YYYY'),'animales sueltos','1','12  ');
INSERT INTO INCIDENT (ID_INCIDENT,DATE_INCIDENT,DESCRIP_INCIDENT,ORDER_ROAD,ID_ROAD) VALUES ('29  ',to_date('11/12/2016','DD/MM/YYYY'),'averia','1','13  ');
INSERT INTO INCIDENT (ID_INCIDENT,DATE_INCIDENT,DESCRIP_INCIDENT,ORDER_ROAD,ID_ROAD) VALUES ('30  ',to_date('11/06/2016','DD/MM/YYYY'),'averia','1','15  ');
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L11037','marco',to_date('12/03/2011','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L12207','samira',to_date('30/12/2014','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L13797','cristina',to_date('09/02/2014','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L16602','javier',to_date('27/09/2015','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L16726','hugo',to_date('13/07/2013','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L17324','isaac',to_date('01/12/2012','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L19705','jorge',to_date('15/08/2011','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L22044','pablo',to_date('01/10/2011','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L22403','cristian',to_date('25/02/2014','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L23636','pablo',to_date('08/02/2012','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L24915','susana',to_date('19/12/2016','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L25691','laura',to_date('05/05/2016','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L27940','pablo',to_date('28/10/2013','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L30883','diego',to_date('25/07/2014','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L32193','sergio',to_date('27/10/2012','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L37032','alba',to_date('02/04/2011','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L44750','juan',to_date('13/11/2011','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L46597','marta',to_date('05/12/2010','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L48257','sergio',to_date('30/08/2013','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L49027','luis',to_date('15/12/2011','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L49175','pablo',to_date('24/07/2010','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L53563','javier',to_date('29/08/2010','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L56298','santiago',to_date('27/01/2014','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L56831','rafael',to_date('23/02/2013','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L59273','javier',to_date('17/06/2013','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L59875','anton',to_date('16/06/2015','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L60591','daniel',to_date('23/11/2012','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L64853','carlos',to_date('23/02/2016','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L66735','cristina',to_date('28/08/2010','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L83345','pablo',to_date('04/08/2010','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L85899','antonio',to_date('10/10/2010','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L86724','raul',to_date('06/11/2010','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L90890','sergio',to_date('08/09/2012','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L91118','julio',to_date('19/03/2016','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L91119','iñaki',to_date('16/11/2013','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L92266','adrian',to_date('22/11/2016','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L94409','sergio',to_date('22/10/2015','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L98063','rodrigo',to_date('23/10/2013','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L98628','daniel',to_date('26/07/2012','DD/MM/YYYY'));
INSERT INTO AGENT (LICENCE,NAME_AGENT,SENIORITY) VALUES ('L99095','jonathan',to_date('17/07/2012','DD/MM/YYYY'));
INSERT INTO PAIRS_WITH (LICENCE1,LICENCE2) VALUES ('L11037','L48257');
INSERT INTO PAIRS_WITH (LICENCE1,LICENCE2) VALUES ('L12207','L48257');
INSERT INTO PAIRS_WITH (LICENCE1,LICENCE2) VALUES ('L12207','L92266');
INSERT INTO PAIRS_WITH (LICENCE1,LICENCE2) VALUES ('L25691','L19705');
INSERT INTO PAIRS_WITH (LICENCE1,LICENCE2) VALUES ('L46597','L56298');
INSERT INTO PAIRS_WITH (LICENCE1,LICENCE2) VALUES ('L48257','L49175');
INSERT INTO PAIRS_WITH (LICENCE1,LICENCE2) VALUES ('L48257','L98628');
INSERT INTO PAIRS_WITH (LICENCE1,LICENCE2) VALUES ('L49027','L49175');
INSERT INTO PAIRS_WITH (LICENCE1,LICENCE2) VALUES ('L49027','L56831');
INSERT INTO PAIRS_WITH (LICENCE1,LICENCE2) VALUES ('L49027','L98628');
INSERT INTO PAIRS_WITH (LICENCE1,LICENCE2) VALUES ('L49175','L91119');
INSERT INTO PAIRS_WITH (LICENCE1,LICENCE2) VALUES ('L53563','L44750');
INSERT INTO PAIRS_WITH (LICENCE1,LICENCE2) VALUES ('L60591','L16602');
INSERT INTO PAIRS_WITH (LICENCE1,LICENCE2) VALUES ('L64853','L11037');
INSERT INTO PAIRS_WITH (LICENCE1,LICENCE2) VALUES ('L66735','L94409');
INSERT INTO PAIRS_WITH (LICENCE1,LICENCE2) VALUES ('L85899','L44750');
INSERT INTO PAIRS_WITH (LICENCE1,LICENCE2) VALUES ('L85899','L64853');
INSERT INTO PAIRS_WITH (LICENCE1,LICENCE2) VALUES ('L92266','L64853');
INSERT INTO PAIRS_WITH (LICENCE1,LICENCE2) VALUES ('L94409','L86724');
INSERT INTO PAIRS_WITH (LICENCE1,LICENCE2) VALUES ('L98063','L32193');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('1   ','L64853','L11037');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('10  ','L49027','L98628');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('10  ','L85899','L64853');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('11  ','L25691','L19705');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('11  ','L98063','L32193');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('12  ','L48257','L49175');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('12  ','L53563','L44750');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('12  ','L94409','L86724');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('15  ','L60591','L16602');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('15  ','L64853','L11037');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('15  ','L98063','L32193');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('16  ','L25691','L19705');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('18  ','L12207','L92266');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('18  ','L25691','L19705');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('19  ','L53563','L44750');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('19  ','L64853','L11037');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('19  ','L66735','L94409');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('20  ','L48257','L98628');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('20  ','L49027','L98628');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('20  ','L92266','L64853');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('20  ','L94409','L86724');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('21  ','L60591','L16602');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('21  ','L94409','L86724');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('21  ','L98063','L32193');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('22  ','L85899','L44750');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('23  ','L46597','L56298');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('23  ','L98063','L32193');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('24  ','L49027','L49175');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('24  ','L98063','L32193');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('25  ','L49027','L49175');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('25  ','L85899','L64853');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('26  ','L98063','L32193');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('27  ','L11037','L48257');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('27  ','L25691','L19705');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('27  ','L49027','L56831');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('27  ','L85899','L64853');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('28  ','L11037','L48257');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('28  ','L46597','L56298');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('28  ','L94409','L86724');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('29  ','L48257','L98628');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('29  ','L66735','L94409');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('30  ','L48257','L49175');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('30  ','L48257','L98628');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('4   ','L48257','L49175');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('5   ','L49175','L91119');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('5   ','L92266','L64853');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('6   ','L49027','L49175');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('7   ','L92266','L64853');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('8   ','L85899','L44750');
INSERT INTO COMES (ID_INCIDENT,LICENCE1,LICENCE2) VALUES ('9   ','L49175','L91119');
INSERT INTO SPONSOR (ID_SPONSOR,NAME_SPONSOR,ID_TM) VALUES ('1   ','junmer','7   ');
INSERT INTO SPONSOR (ID_SPONSOR,NAME_SPONSOR,ID_TM) VALUES ('2   ','mushiya','9   ');
INSERT INTO SPONSOR (ID_SPONSOR,NAME_SPONSOR,ID_TM) VALUES ('3   ','staii','23  ');
INSERT INTO SPONSOR (ID_SPONSOR,NAME_SPONSOR,ID_TM) VALUES ('4   ','chank','18  ');
INSERT INTO SPONSOR (ID_SPONSOR,NAME_SPONSOR,ID_TM) VALUES ('5   ','medai','20  ');
INSERT INTO SPONSOR (ID_SPONSOR,NAME_SPONSOR,ID_TM) VALUES ('6   ','caist','9   ');
INSERT INTO SPONSOR (ID_SPONSOR,NAME_SPONSOR,ID_TM) VALUES ('7   ','coadeva','5   ');
INSERT INTO SPONSOR (ID_SPONSOR,NAME_SPONSOR,ID_TM) VALUES ('8   ','firentre','15  ');
INSERT INTO SPONSOR (ID_SPONSOR,NAME_SPONSOR,ID_TM) VALUES ('9   ','brave','28  ');
INSERT INTO SPONSOR (ID_SPONSOR,NAME_SPONSOR,ID_TM) VALUES ('10  ','pepord','17  ');
INSERT INTO SPONSOR (ID_SPONSOR,NAME_SPONSOR,ID_TM) VALUES ('11  ','prohl','1   ');
INSERT INTO SPONSOR (ID_SPONSOR,NAME_SPONSOR,ID_TM) VALUES ('12  ','bratek','15  ');
INSERT INTO SPONSOR (ID_SPONSOR,NAME_SPONSOR,ID_TM) VALUES ('13  ','cogrus','1   ');
INSERT INTO SPONSOR (ID_SPONSOR,NAME_SPONSOR,ID_TM) VALUES ('14  ','indir','28  ');
INSERT INTO SPONSOR (ID_SPONSOR,NAME_SPONSOR,ID_TM) VALUES ('15  ','punden','16  ');
INSERT INTO SPONSOR (ID_SPONSOR,NAME_SPONSOR,ID_TM) VALUES ('16  ','ofe','1   ');
INSERT INTO SPONSOR (ID_SPONSOR,NAME_SPONSOR,ID_TM) VALUES ('17  ','gentine','11  ');
INSERT INTO SPONSOR (ID_SPONSOR,NAME_SPONSOR,ID_TM) VALUES ('18  ','minge','15  ');
INSERT INTO SPONSOR (ID_SPONSOR,NAME_SPONSOR,ID_TM) VALUES ('19  ','auras','28  ');
INSERT INTO SPONSOR (ID_SPONSOR,NAME_SPONSOR,ID_TM) VALUES ('20  ','nuten','30  ');
INSERT INTO TEAM (NAME_TEAM,CITY_TEAM,BUDGET) VALUES ('trend','oviedo','88000');
INSERT INTO TEAM (NAME_TEAM,CITY_TEAM,BUDGET) VALUES ('dean','santander','69100');
INSERT INTO TEAM (NAME_TEAM,CITY_TEAM,BUDGET) VALUES ('magnus','vigo','90300');
INSERT INTO TEAM (NAME_TEAM,CITY_TEAM,BUDGET) VALUES ('lowe','zaragoza','94400');
INSERT INTO TEAM (NAME_TEAM,CITY_TEAM,BUDGET) VALUES ('millar','gerona','99700');
INSERT INTO TEAM (NAME_TEAM,CITY_TEAM,BUDGET) VALUES ('vande','alicante','91200');
INSERT INTO TEAM (NAME_TEAM,CITY_TEAM,BUDGET) VALUES ('peat','granada','60900');
INSERT INTO TEAM (NAME_TEAM,CITY_TEAM,BUDGET) VALUES ('eisel','toledo','97100');
INSERT INTO TEAM (NAME_TEAM,CITY_TEAM,BUDGET) VALUES ('garmin','badajoz','71800');
INSERT INTO TEAM (NAME_TEAM,CITY_TEAM,BUDGET) VALUES ('slip','salamanca','60300');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('dean','2   ','83200');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('dean','13  ','70100');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('dean','19  ','29500');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('eisel','13  ','65500');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('garmin','15  ','89300');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('garmin','16  ','88400');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('lowe','1   ','83500');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('lowe','2   ','51900');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('lowe','8   ','54400');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('magnus','2   ','61000');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('magnus','10  ','31300');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('magnus','14  ','34100');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('magnus','16  ','72200');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('magnus','20  ','10900');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('millar','7   ','87200');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('millar','8   ','56300');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('millar','10  ','84600');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('millar','13  ','89200');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('millar','17  ','58000');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('peat','12  ','15600');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('peat','17  ','32400');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('peat','18  ','79400');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('slip','1   ','36800');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('slip','5   ','22000');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('slip','7   ','85900');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('slip','8   ','59900');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('slip','9   ','69700');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('slip','13  ','50600');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('slip','14  ','88600');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('slip','15  ','76100');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('slip','17  ','49000');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('slip','19  ','10900');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('trend','14  ','84200');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('trend','15  ','47900');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('trend','17  ','38200');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('trend','19  ','80500');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('vande','3   ','27200');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('vande','10  ','42200');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('vande','13  ','28100');
INSERT INTO IS_SPONSORIZED (NAME_TEAM,ID_SPONSOR,AMOUNT) VALUES ('vande','17  ','32400');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('alberto','senior','esprinter','millar');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('alejandro','elite','escalador','trend');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('antonio','elite','esprinter','trend');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('carla','elite','rodador','eisel');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('carmen','elite','rodador','slip');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('claudia','senior','escalador','eisel');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('cova','senior','clasicomano','millar');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('daniel','master','escalador','eisel');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('diego','elite','rodador','peat');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('eduardo','senior','rodador','trend');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('enol','senior','clasicomano','peat');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('eva','elite','clasicomano','vande');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('fernando','elite','esprinter','trend');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('guillermo','senior','clasicomano','magnus');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('isabel','elite','clasicomano','magnus');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('itziar','elite','clasicomano','vande');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('jorge','master','esprinter','eisel');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('juan','master','clasicomano','garmin');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('laura','senior','clasicomano','eisel');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('leticia','elite','clasicomano','trend');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('lorena','elite','rodador','peat');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('lucas','master','esprinter','magnus');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('mar','elite','esprinter','garmin');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('marcos','elite','esprinter','garmin');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('marta','elite','clasicomano','eisel');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('mateo','senior','escalador','lowe');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('mauro','master','rodador','dean');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('miguel','master','clasicomano','vande');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('natalia','elite','esprinter','trend');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('nerea','senior','escalador','peat');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('olaya','elite','escalador','millar');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('oliver','senior','clasicomano','lowe');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('pablo','senior','clasicomano','eisel');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('paula','elite','escalador','eisel');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('pelayo','elite','escalador','garmin');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('raquel','senior','esprinter','magnus');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('roberto','elite','rodador','eisel');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('samuel','master','clasicomano','millar');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('sara','senior','esprinter','millar');
INSERT INTO CYCLIST (CYCLIST_NAME,CATEGORY_CYCLIST,TYPE_CYCLIST,NAME_TEAM) VALUES ('sergio','senior','escalador','magnus');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('1','fernando','1');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('1','guillermo','2');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('1','lorena','3');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('1','pelayo','5');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('1','roberto','4');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('2','leticia','2');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('2','lucas','3');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('2','mar','5');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('2','marta','8');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('2','mateo','6');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('2','mauro','4');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('2','natalia','9');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('2','oliver','1');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('2','sara','7');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('3','diego','4');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('3','itziar','1');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('3','miguel','2');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('3','paula','3');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('3','sergio','5');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('4','isabel','3');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('4','juan','2');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('4','roberto','1');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('5','alberto','5');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('5','alejandro','1');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('5','carmen','3');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('5','daniel','4');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('5','leticia','2');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('6','eva','3');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('6','guillermo','1');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('6','paula','2');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('7','cova','6');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('7','daniel','7');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('7','itziar','2');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('7','leticia','1');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('7','lorena','5');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('7','roberto','4');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('7','sara','3');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('8','leticia','1');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('8','mar','3');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('8','roberto','2');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('9','claudia','1');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('9','guillermo','4');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('9','laura','3');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('9','miguel','2');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('9','raquel','5');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('10','antonio','3');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('10','enol','6');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('10','fernando','2');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('10','leticia','1');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('10','lucas','5');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('10','pelayo','4');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('10','sara','7');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('11','alejandro','6');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('11','carmen','4');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('11','jorge','3');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('11','lucas','7');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('11','oliver','1');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('11','raquel','2');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('11','roberto','5');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('12','eva','2');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('12','pablo','3');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('12','sergio','1');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('13','nerea','1');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('14','itziar','1');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('14','pelayo','2');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('15','antonio','1');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('15','claudia','2');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('15','isabel','3');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('16','carla','3');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('16','enol','1');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('16','paula','2');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('17','daniel','1');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('17','marcos','4');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('17','raquel','3');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('17','sergio','2');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('18','alejandro','4');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('18','carla','2');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('18','juan','5');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('18','natalia','1');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('18','oliver','6');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('18','pablo','7');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('18','pelayo','3');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('19','alberto','4');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('19','alejandro','7');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('19','enol','3');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('19','fernando','5');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('19','lucas','6');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('19','mauro','1');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('19','oliver','2');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('19','paula','8');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('20','antonio','4');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('20','claudia','5');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('20','eva','6');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('20','oliver','3');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('20','pablo','1');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('20','raquel','2');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('21','enol','2');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('21','mar','1');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('21','mateo','3');
INSERT INTO TAKES_PART (NUM_STAGE,CYCLIST_NAME,ORDER_CLASSIFICATION) VALUES ('21','roberto','4');
INSERT INTO MAILLOT (ID_MAILLOT,COLOR,MEANING) VALUES ('1   ','verde','lider clasificación por puntos');
INSERT INTO MAILLOT (ID_MAILLOT,COLOR,MEANING) VALUES ('2   ','rojo','líder de la general individual');
INSERT INTO MAILLOT (ID_MAILLOT,COLOR,MEANING) VALUES ('3   ','azul','líder clasificación de montaña');
INSERT INTO MAILLOT (ID_MAILLOT,COLOR,MEANING) VALUES ('4   ','blanco','líder de la clasificación combinada');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('1','fernando','1   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('1','fernando','2   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('2','oliver','1   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('2','oliver','2   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('3','itziar','1   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('3','itziar','2   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('4','roberto','1   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('4','roberto','2   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('4','roberto','3   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('5','alejandro','1   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('5','alejandro','2   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('5','alejandro','3   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('6','guillermo','1   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('6','guillermo','2   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('7','leticia','1   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('7','leticia','2   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('8','leticia','1   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('8','leticia','2   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('9','claudia','2   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('9','claudia','3   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('10','leticia','1   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('10','leticia','2   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('10','leticia','3   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('11','oliver','2   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('12','sergio','2   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('13','nerea','2   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('14','itziar','2   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('15','antonio','2   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('16','enol','2   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('16','enol','3   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('17','daniel','2   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('17','daniel','3   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('18','natalia','2   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('18','natalia','3   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('19','mauro','2   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('20','pablo','2   ');
INSERT INTO WEARS (NUM_STAGE,CYCLIST_NAME,ID_MAILLOT) VALUES ('21','mar','2   ');