DROP TABLE COMPRA;
DROP TABLE ESREALIZADA;
DROP TABLE AGENCIA;
DROP TABLE MAYORISTA;
DROP TABLE TIENE;
DROP TABLE DESCUENTOS;
DROP TABLE CLIENTE CASCADE CONSTRAINTS;
DROP TABLE OFERTA;

CREATE TABLE "OFERTA"
(
   CODOFERTA varchar(5) NOT NULL,
   ORIGEN varchar(40),
   DESTINO varchar(40),
   CONSTRAINT PK_OFERTA PRIMARY KEY (CODOFERTA)
);

CREATE TABLE "CLIENTE"
(
   DNI varchar(9) NOT NULL,
   NOMBRE varchar(40),
   CONSTRAINT PK_CLIENTE PRIMARY KEY (DNI)
);

CREATE TABLE "DESCUENTOS"
(
   CODDESCUENTO varchar(5) NOT NULL,
   PORCENTAJE decimal(12,3),
   CONSTRAINT PK_DESCUENTOS PRIMARY KEY (CODDESCUENTO)
);

CREATE TABLE "TIENE"
(
   CODDESCUENTO varchar(5) NOT NULL,
   DNI varchar(8) NOT NULL,
   CONSTRAINT PK_TIENE PRIMARY KEY (CODDESCUENTO,DNI),
   CONSTRAINT FK_TIENE_CLIENTE FOREIGN KEY (DNI) REFERENCES "CLIENTE" (DNI),
   CONSTRAINT FK_TIENE_DESCUENTOS FOREIGN KEY (CODDESCUENTO) REFERENCES "DESCUENTOS" (CODDESCUENTO)
);

CREATE TABLE "MAYORISTA"
(
   CODMAYORISTA varchar(5) NOT NULL,
   NOMBREMAYORISTA varchar(40),
   TIPO varchar(20),
   CONSTRAINT PK_MAYORISTA PRIMARY KEY (CODMAYORISTA)
);

CREATE TABLE "AGENCIA"
(
   CODAGENCIA varchar(5) NOT NULL,
   NOMBREAGENCIA varchar(40),
   VENTASREALIZADAS decimal(12,3),
   CODMAYORISTA varchar(5) NOT NULL,
   CONSTRAINT PK_AGENCIA PRIMARY KEY (CODAGENCIA),
   CONSTRAINT FK_AGENCIA_MAYORISTA FOREIGN KEY (CODMAYORISTA) REFERENCES "MAYORISTA" (CODMAYORISTA)
);

CREATE TABLE "ESREALIZADA"
(
   CODOFERTA varchar(5) NOT NULL,
   CODAGENCIA varchar(5) NOT NULL,
   PRECIO decimal(12,3),
   PLAZASDISPONIBLES decimal(12,3),
   CONSTRAINT PK_ESREALIZADA PRIMARY KEY (CODOFERTA,CODAGENCIA),
   CONSTRAINT FK_ESREALIZADA_OFERTA FOREIGN KEY (CODOFERTA) REFERENCES "OFERTA" (CODOFERTA),
   CONSTRAINT FK_ESREALIZADA_AGENCIA FOREIGN KEY (CODAGENCIA) REFERENCES "AGENCIA" (CODAGENCIA)   
);

CREATE TABLE "COMPRA"
(
   DNI varchar(9) NOT NULL,
   CODAGENCIA varchar(5) NOT NULL,
   CODOFERTA varchar(5) NOT NULL,
   PAGOFRACCIONADO varchar(1),
   IMPORTEDEFINITIVO decimal(12,3),
   CONSTRAINT PK_COMPRA PRIMARY KEY (DNI,CODAGENCIA,CODOFERTA),
   CONSTRAINT FK_COMPRA_Cliente FOREIGN KEY (DNI) REFERENCES "CLIENTE" (DNI),
   CONSTRAINT FK_COMPRA_ESREALIZADA FOREIGN KEY (CODAGENCIA,CODOFERTA) REFERENCES "ESREALIZADA" (CODAGENCIA,CODOFERTA)
);

INSERT INTO "OFERTA" (CODOFERTA,ORIGEN,DESTINO) VALUES ('of1','Madrid','Ginebra');
INSERT INTO "OFERTA" (CODOFERTA,ORIGEN,DESTINO) VALUES ('of2','Barcelona','Bruselas');
INSERT INTO "OFERTA" (CODOFERTA,ORIGEN,DESTINO) VALUES ('of3','Oviedo','Ginebra');
INSERT INTO "OFERTA" (CODOFERTA,ORIGEN,DESTINO) VALUES ('of4','Madrid','Milan');
INSERT INTO "OFERTA" (CODOFERTA,ORIGEN,DESTINO) VALUES ('of5','Madrid','Ginebra');
INSERT INTO "OFERTA" (CODOFERTA,ORIGEN,DESTINO) VALUES ('of6','Barcelona','Milan');
INSERT INTO "OFERTA" (CODOFERTA,ORIGEN,DESTINO) VALUES ('of7','Barcelona','Bruselas');

INSERT INTO "CLIENTE" (DNI,NOMBRE) VALUES (1,'Paco Fernández');
INSERT INTO "CLIENTE" (DNI,NOMBRE) VALUES (2,'Carmen Pérez');
INSERT INTO "CLIENTE" (DNI,NOMBRE) VALUES (3,'Antonio �?lvarez');
INSERT INTO "CLIENTE" (DNI,NOMBRE) VALUES (4,'Bernardo Boquerón');
INSERT INTO "CLIENTE" (DNI,NOMBRE) VALUES (5,'Carlos Cifuentes');
INSERT INTO "CLIENTE" (DNI,NOMBRE) VALUES (6,'Damián Durán');
INSERT INTO "CLIENTE" (DNI,NOMBRE) VALUES (7,'Ernesto Estévez');
INSERT INTO "CLIENTE" (DNI,NOMBRE) VALUES (8,'Fernando Fidalgo');
INSERT INTO "CLIENTE" (DNI,NOMBRE) VALUES (9,'José García');
INSERT INTO "CLIENTE" (DNI,NOMBRE) VALUES (10,'María Iglésias');

INSERT INTO "DESCUENTOS" (CODDESCUENTO,PORCENTAJE) VALUES ('d1',5);
INSERT INTO "DESCUENTOS" (CODDESCUENTO,PORCENTAJE) VALUES ('d10',4);
INSERT INTO "DESCUENTOS" (CODDESCUENTO,PORCENTAJE) VALUES ('d2',6);
INSERT INTO "DESCUENTOS" (CODDESCUENTO,PORCENTAJE) VALUES ('d3',2);
INSERT INTO "DESCUENTOS" (CODDESCUENTO,PORCENTAJE) VALUES ('d4',1);
INSERT INTO "DESCUENTOS" (CODDESCUENTO,PORCENTAJE) VALUES ('d5',15);
INSERT INTO "DESCUENTOS" (CODDESCUENTO,PORCENTAJE) VALUES ('d6',2);
INSERT INTO "DESCUENTOS" (CODDESCUENTO,PORCENTAJE) VALUES ('d7',3);
INSERT INTO "DESCUENTOS" (CODDESCUENTO,PORCENTAJE) VALUES ('d8',3);
INSERT INTO "DESCUENTOS" (CODDESCUENTO,PORCENTAJE) VALUES ('d9',2);

INSERT INTO "TIENE" (CODDESCUENTO,DNI) VALUES ('d1','1');
INSERT INTO "TIENE" (CODDESCUENTO,DNI) VALUES ('d1','3');
INSERT INTO "TIENE" (CODDESCUENTO,DNI) VALUES ('d1','4');
INSERT INTO "TIENE" (CODDESCUENTO,DNI) VALUES ('d10','2');
INSERT INTO "TIENE" (CODDESCUENTO,DNI) VALUES ('d2','1');
INSERT INTO "TIENE" (CODDESCUENTO,DNI) VALUES ('d2','6');
INSERT INTO "TIENE" (CODDESCUENTO,DNI) VALUES ('d3','5');
INSERT INTO "TIENE" (CODDESCUENTO,DNI) VALUES ('d7','10');
INSERT INTO "TIENE" (CODDESCUENTO,DNI) VALUES ('d7','5');
INSERT INTO "TIENE" (CODDESCUENTO,DNI) VALUES ('d7','9');
INSERT INTO "TIENE" (CODDESCUENTO,DNI) VALUES ('d8','7');

INSERT INTO "MAYORISTA" (CODMAYORISTA,NOMBREMAYORISTA,TIPO) VALUES ('may1','Mayorista1','vuelos');
INSERT INTO "MAYORISTA" (CODMAYORISTA,NOMBREMAYORISTA,TIPO) VALUES ('may2','Mayorista2','combinados');
INSERT INTO "MAYORISTA" (CODMAYORISTA,NOMBREMAYORISTA,TIPO) VALUES ('may3','Mayorista3','combinados');
INSERT INTO "MAYORISTA" (CODMAYORISTA,NOMBREMAYORISTA,TIPO) VALUES ('may4','Mayorista4','hoteles');
INSERT INTO "MAYORISTA" (CODMAYORISTA,NOMBREMAYORISTA,TIPO) VALUES ('may5','Mayorista5','combinados');
INSERT INTO "MAYORISTA" (CODMAYORISTA,NOMBREMAYORISTA,TIPO) VALUES ('may6','Mayorista6','cruceros');
INSERT INTO "MAYORISTA" (CODMAYORISTA,NOMBREMAYORISTA,TIPO) VALUES ('may7','Mayorista7','combinados');
INSERT INTO "MAYORISTA" (CODMAYORISTA,NOMBREMAYORISTA,TIPO) VALUES ('may8','Mayorista8','cruceros');

INSERT INTO "AGENCIA" (CODAGENCIA,NOMBREAGENCIA,VENTASREALIZADAS,CODMAYORISTA) VALUES ('ag1','Agencia1',5,'may2');
INSERT INTO "AGENCIA" (CODAGENCIA,NOMBREAGENCIA,VENTASREALIZADAS,CODMAYORISTA) VALUES ('ag2','Agencia2',1,'may2');
INSERT INTO "AGENCIA" (CODAGENCIA,NOMBREAGENCIA,VENTASREALIZADAS,CODMAYORISTA) VALUES ('ag3','Agencia3',1,'may4');
INSERT INTO "AGENCIA" (CODAGENCIA,NOMBREAGENCIA,VENTASREALIZADAS,CODMAYORISTA) VALUES ('ag4','Agencia4',1,'may5');
INSERT INTO "AGENCIA" (CODAGENCIA,NOMBREAGENCIA,VENTASREALIZADAS,CODMAYORISTA) VALUES ('ag5','Agencia5',1,'may7');
INSERT INTO "AGENCIA" (CODAGENCIA,NOMBREAGENCIA,VENTASREALIZADAS,CODMAYORISTA) VALUES ('ag6','Agencia6',2,'may5');
INSERT INTO "AGENCIA" (CODAGENCIA,NOMBREAGENCIA,VENTASREALIZADAS,CODMAYORISTA) VALUES ('ag7','Agencia7',0,'may4');

INSERT INTO "ESREALIZADA" (CODOFERTA,CODAGENCIA,PRECIO,PLAZASDISPONIBLES) VALUES ('of1','ag1',100,2);
INSERT INTO "ESREALIZADA" (CODOFERTA,CODAGENCIA,PRECIO,PLAZASDISPONIBLES) VALUES ('of1','ag6',115,1);
INSERT INTO "ESREALIZADA" (CODOFERTA,CODAGENCIA,PRECIO,PLAZASDISPONIBLES) VALUES ('of1','ag2',200,4);
INSERT INTO "ESREALIZADA" (CODOFERTA,CODAGENCIA,PRECIO,PLAZASDISPONIBLES) VALUES ('of2','ag3',1140,4);
INSERT INTO "ESREALIZADA" (CODOFERTA,CODAGENCIA,PRECIO,PLAZASDISPONIBLES) VALUES ('of2','ag1',1000,2);
INSERT INTO "ESREALIZADA" (CODOFERTA,CODAGENCIA,PRECIO,PLAZASDISPONIBLES) VALUES ('of2','ag4',900,0);
INSERT INTO "ESREALIZADA" (CODOFERTA,CODAGENCIA,PRECIO,PLAZASDISPONIBLES) VALUES ('of3','ag6',1500,11);
INSERT INTO "ESREALIZADA" (CODOFERTA,CODAGENCIA,PRECIO,PLAZASDISPONIBLES) VALUES ('of3','ag5',1450,1);
INSERT INTO "ESREALIZADA" (CODOFERTA,CODAGENCIA,PRECIO,PLAZASDISPONIBLES) VALUES ('of3','ag1',2000,1);
INSERT INTO "ESREALIZADA" (CODOFERTA,CODAGENCIA,PRECIO,PLAZASDISPONIBLES) VALUES ('of5','ag1',300,1);
INSERT INTO "ESREALIZADA" (CODOFERTA,CODAGENCIA,PRECIO,PLAZASDISPONIBLES) VALUES ('of7','ag2',1270,1);
INSERT INTO "ESREALIZADA" (CODOFERTA,CODAGENCIA,PRECIO,PLAZASDISPONIBLES) VALUES ('of7','ag1',1200,1);

INSERT INTO "COMPRA" (DNI,CODAGENCIA,CODOFERTA,PAGOFRACCIONADO,IMPORTEDEFINITIVO) VALUES (1,'ag1','of1','S',223342);
INSERT INTO "COMPRA" (DNI,CODAGENCIA,CODOFERTA,PAGOFRACCIONADO,IMPORTEDEFINITIVO) VALUES (1,'ag3','of2','N',15151);
INSERT INTO "COMPRA" (DNI,CODAGENCIA,CODOFERTA,PAGOFRACCIONADO,IMPORTEDEFINITIVO) VALUES (1,'ag4','of2','N',123);
INSERT INTO "COMPRA" (DNI,CODAGENCIA,CODOFERTA,PAGOFRACCIONADO,IMPORTEDEFINITIVO) VALUES (2,'ag1','of1','N',223342);
INSERT INTO "COMPRA" (DNI,CODAGENCIA,CODOFERTA,PAGOFRACCIONADO,IMPORTEDEFINITIVO) VALUES (2,'ag3','of2','S',15151);
INSERT INTO "COMPRA" (DNI,CODAGENCIA,CODOFERTA,PAGOFRACCIONADO,IMPORTEDEFINITIVO) VALUES (2,'ag6','of3','S',1235);
INSERT INTO "COMPRA" (DNI,CODAGENCIA,CODOFERTA,PAGOFRACCIONADO,IMPORTEDEFINITIVO) VALUES (3,'ag1','of1','S',150000);
INSERT INTO "COMPRA" (DNI,CODAGENCIA,CODOFERTA,PAGOFRACCIONADO,IMPORTEDEFINITIVO) VALUES (4,'ag1','of1','S',123000);
INSERT INTO "COMPRA" (DNI,CODAGENCIA,CODOFERTA,PAGOFRACCIONADO,IMPORTEDEFINITIVO) VALUES (5,'ag3','of2','S',15151);
INSERT INTO "COMPRA" (DNI,CODAGENCIA,CODOFERTA,PAGOFRACCIONADO,IMPORTEDEFINITIVO) VALUES (5,'ag5','of3','N',12345);
COMMIT;