-- PRÁCTICA SQL4:
-- Ejercicio 1:
--Mostrar los nombres de los clientes con cuentas y préstamos en la sucursal Perryridge. Realizar
--la consulta de varias formas diferentes.
--Utilizando exists:
SELECT CL.NOMBRE_CLIENTE FROM CLIENTE CL
    WHERE EXISTS (SELECT * FROM CUENTA CU, DEPOSITANTE DE
        WHERE CL.NOMBRE_CLIENTE=DE.NOMBRE_CLIENTE AND DE.NUM_CUENTA=CU.NUM_CUENTA 
        AND CU.NOMBRE_SUCURSAL='Perryridge')
    AND EXISTS (SELECT * FROM PRESTAMO PE, PRESTATARIO PR
        WHERE CL.NOMBRE_CLIENTE=PR.NOMBRE_CLIENTE AND PR.NUM_PRESTAMO=PE.NUM_PRESTAMO
        AND PE.NOMBRE_SUCURSAL='Perryridge');
--Utilizando in:
SELECT CL.NOMBRE_CLIENTE FROM CLIENTE CL
    WHERE CL.NOMBRE_CLIENTE IN (SELECT DE.NOMBRE_CLIENTE FROM CUENTA CU, DEPOSITANTE DE
        WHERE DE.NUM_CUENTA=CU.NUM_CUENTA AND CU.NOMBRE_SUCURSAL='Perryridge')
    AND CL.NOMBRE_CLIENTE IN (SELECT PR.NOMBRE_CLIENTE FROM PRESTAMO PE, PRESTATARIO PR
        WHERE PR.NUM_PRESTAMO=PE.NUM_PRESTAMO AND PE.NOMBRE_SUCURSAL='Perryridge');
--Utilizando el producto de tablas:
SELECT DE.NOMBRE_CLIENTE FROM DEPOSITANTE DE 
    INNER JOIN CUENTA CA ON CA.NUM_CUENTA=DE.NUM_CUENTA
    INNER JOIN PRESTATARIO PR ON PR.NOMBRE_CLIENTE=DE.NOMBRE_CLIENTE
    INNER JOIN PRESTAMO PE ON PE.NUM_PRESTAMO=PR.NUM_PRESTAMO
    WHERE CA.NOMBRE_SUCURSAl = 'Perryridge' AND PE.NOMBRE_SUCURSAL='Perryridge';    
--Utilizando intersect:
SELECT NOMBRE_CLIENTE FROM CUENTA CA, DEPOSITANTE DE
    WHERE CA.NUM_CUENTA=DE.NUM_CUENTA AND CA.NOMBRE_SUCURSAL='Perryridge'
INTERSECT (SELECT NOMBRE_CLIENTE FROM PRESTAMO PE, PRESTATARIO PR
    WHERE PE.NUM_PRESTAMO=PR.NUM_PRESTAMO AND PE.NOMBRE_SUCURSAL='Perryridge');

-- Ejercicio 2:
--Mostrar los nombres de los clientes con cuentas, pero sin préstamos en la sucursal Perryridge.
--Realizar la consulta de varias formas diferentes.
--Utilizando exists/not exists:
SELECT CL.NOMBRE_CLIENTE FROM CLIENTE CL
    WHERE EXISTS (SELECT * FROM CUENTA CU, DEPOSITANTE DE
        WHERE CL.NOMBRE_CLIENTE=DE.NOMBRE_CLIENTE AND DE.NUM_CUENTA=CU.NUM_CUENTA 
        AND CU.NOMBRE_SUCURSAL='Perryridge')
    AND NOT EXISTS (SELECT * FROM PRESTAMO PE, PRESTATARIO PR
        WHERE CL.NOMBRE_CLIENTE=PR.NOMBRE_CLIENTE AND PR.NUM_PRESTAMO=PE.NUM_PRESTAMO
        AND PE.NOMBRE_SUCURSAL='Perryridge');
--Utilizando in/not in:
SELECT CL.NOMBRE_CLIENTE FROM CLIENTE CL
    WHERE CL.NOMBRE_CLIENTE IN (SELECT DE.NOMBRE_CLIENTE FROM CUENTA CU, DEPOSITANTE DE
        WHERE DE.NUM_CUENTA=CU.NUM_CUENTA AND CU.NOMBRE_SUCURSAL='Perryridge')
    AND CL.NOMBRE_CLIENTE NOT IN (SELECT PR.NOMBRE_CLIENTE FROM PRESTAMO PE, PRESTATARIO PR
        WHERE PR.NUM_PRESTAMO=PE.NUM_PRESTAMO AND PE.NOMBRE_SUCURSAL='Perryridge');  
--Utilizando minus/except:
SELECT NOMBRE_CLIENTE FROM CUENTA CA, DEPOSITANTE DE
    WHERE CA.NUM_CUENTA=DE.NUM_CUENTA AND CA.NOMBRE_SUCURSAL='Perryridge'
MINUS (SELECT NOMBRE_CLIENTE FROM PRESTAMO PE, PRESTATARIO PR
    WHERE PE.NUM_PRESTAMO=PR.NUM_PRESTAMO AND PE.NOMBRE_SUCURSAL='Perryridge');
    
-- Ejercicio 3:
--Mostrar los nombres de los clientes con cuentas en la sucursal en la que tiene cuentas el cliente
--Hayes.
SELECT DISTINCT NOMBRE_CLIENTE FROM DEPOSITANTE DE, CUENTA CA 
    WHERE DE.NUM_CUENTA=CA.NUM_CUENTA AND CA.NOMBRE_SUCURSAL IN (
        SELECT NOMBRE_SUCURSAL FROM CUENTA CA2, DEPOSITANTE DE2 
            WHERE CA2.NUM_CUENTA=DE2.NUM_CUENTA AND DE2.NOMBRE_CLIENTE='Hayes');
            
-- Ejercicio 4:
--Mostrar los nombres de las sucursales cuyo activo es mayor que el activo de alguna sucursal de
--Brooklyn.
SELECT NOMBRE_SUCURSAL FROM SUCURSAL WHERE ACTIVO > 
    ANY(SELECT ACTIVO FROM SUCURSAL WHERE CIUDAD_SUCURSAL='Brooklyn');
    
-- Ejercicio 5:
--Mostrar los nombres de las sucursales cuyo activo es mayor que el activo de todas las
--sucursales de Brooklyn.
SELECT NOMBRE_SUCURSAL FROM SUCURSAL WHERE ACTIVO > 
    ALL(SELECT ACTIVO FROM SUCURSAL WHERE CIUDAD_SUCURSAL='Brooklyn');
    
-- Ejercicio 6:
--Mostrar los nombres de los clientes de la sucursal Perryridge en orden alfabético.
SELECT NOMBRE_CLIENTE FROM DEPOSITANTE DE, CUENTA CA
    WHERE DE.NUM_CUENTA=CA.NUM_CUENTA AND CA.NOMBRE_SUCURSAL='Perryridge' 
UNION (SELECT NOMBRE_CLIENTE FROM PRESTATARIO PR, PRESTAMO PE
    WHERE PR.NUM_PRESTAMO=PE.NUM_PRESTAMO AND PE.NOMBRE_SUCURSAL='Perryridge')
ORDER BY NOMBRE_CLIENTE;

-- Ejercicio 7:
--Mostrar el nombre de las sucursales que tienen el mayor promedio de saldos.
SELECT NOMBRE_SUCURSAL FROM CUENTA GROUP BY NOMBRE_SUCURSAL
    HAVING AVG(SALDO) >= ALL(SELECT AVG(SALDO) FROM CUENTA GROUP BY NOMBRE_SUCURSAL);

-- Ejercicio 8:
--Mostrar el promedio de los saldos de todos los clientes de la ciudad de Harrison que tienen al
--menos dos cuentas.
SELECT AVG(SALDO) AS SALDO_MEDIO FROM CUENTA CA, DEPOSITANTE DE, CLIENTE CL
    WHERE CL.NOMBRE_CLIENTE=DE.NOMBRE_CLIENTE AND DE.NUM_CUENTA=CA.NUM_CUENTA AND CL.CIUDAD_CLIENTE='Harrison'
        GROUP BY DE.NOMBRE_CLIENTE HAVING COUNT(*)>=2;